name: Auto Merge Any PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Authenticate with PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "$GH_PAT" | gh auth login --with-token

      - name: Auto-merge PR
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          echo "Auto-merging PR #$PR_NUMBER in $REPO"
          gh pr merge $PR_NUMBER --merge --admin --repo $REPO || \
          { echo "Merge failed, maybe conflicts or checks not passed"; exit 1; }
