name: Auto Merge PRs from main (fork-safe)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    if: github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Auto merge PR if source is main (from pull_request_target)
      env:
        TOKEN: ${{ secrets.GH_PAT }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        echo "Merging PR #$PR_NUMBER from branch 'main'"

        response=$(curl -s -X PUT \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/merge" \
          -d '{"commit_title":"Auto merge PR #'"$PR_NUMBER"'","merge_method":"merge"}')

        if echo "$response" | grep -q '"merged":true'; then
          echo "PR #$PR_NUMBER merged successfully."
        else
          echo "Failed to merge PR #$PR_NUMBER. Response:"
          echo "$response"
          exit 1
        fi
