name: Auto Merge PRs into main

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  auto-merge:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge PR into main
        uses: peter-evans/enable-pull-request-automerge@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: merge
