name: Auto Merge PRs from main to main

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-merge:
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Auto-merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Attempting to auto-merge PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --merge --admin --repo "${{ github.repository }}"
