name: Auto Merge All PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Authenticate with PAT
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Auto-merge pull request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Attempting to auto-merge PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --merge --admin --repo "${{ github.repository }}"
