name: Auto Merge PRs from main

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  auto-merge:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Merge the PR
          uses: peter-evans/pull-request-merge@v3
          with:
            token: ${{ secrets.PERSONAL_TOKEN }}
            pull-request: ${{ github.event.pull_request.number }}
            merge-method: merge
