name: Auto Merge PRs to Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Token is set? ${GH_TOKEN:+yes}"   # Just prints 'yes' if token exists
          gh auth status || echo "Not authenticated"

      - name: Merge the PR
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --delete-branch --admin
